version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ".:/app"
    links:
      - redis
    command: [ "modd", "-f", "modd-web.conf" ]
  grpc-web:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - ".:/app"
    links:
      - redis
    command: [ "modd", "-f", "modd-grpc-web.conf" ]
  redis:
    image: "redis:alpine"
    volumes:
      - "./data:/data"
    ports:
      - "6379:6379"
