version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ".:/app"
    links:
      - redis
  redis:
    image: "redis:alpine"
    volumes:
      - "./data:/data"
    ports:
      - "6379:6379"
